(() => {
'use strict';
const VERSION='38'; document.documentElement.dataset.elev8miVersion=VERSION;
// Sky-driven palette shared by logo + 528Hz equalizer.
function syncSky(){const c=window.elev8miCelestial,phase=c?.phase||'night';document.documentElement.dataset.skyPhase=phase;const s=document.documentElement.style;if(phase==='day'){s.setProperty('--sky-accent','#ffcf70');s.setProperty('--sky-accent-2','#71d8ff')}else if(phase==='sunrise'||phase==='sunset'){s.setProperty('--sky-accent','#d879ff');s.setProperty('--sky-accent-2','#ffad78')}else{s.setProperty('--sky-accent','#b990ff');s.setProperty('--sky-accent-2','#7fdcff')}}
setInterval(syncSky,500);syncSky();
// Wing overlays are clipped duplicates: central wordmark remains still.
function wings(){const sigil=document.querySelector('.hero-sigil'),img=sigil?.querySelector('#heroLogo,#flyLogo');if(!sigil||!img||sigil.querySelector('.logo-wing'))return;['left','right'].forEach(side=>{const w=img.cloneNode();w.removeAttribute('id');w.removeAttribute('alt');w.setAttribute('aria-hidden','true');w.className='logo-wing '+side;sigil.append(w)});} setTimeout(wings,1200);setInterval(wings,1500);
// Location controller. NYC is the explicit default used by the sidereal view.
const DEFAULT={lat:40.7128,lon:-74.0060,label:'New York City'};let loc={...DEFAULT};try{loc={...loc,...JSON.parse(localStorage.getItem('elev8mi-location')||'{}')}}catch(_){}
window.Elev8Location={get current(){return {...loc}},set(v){loc={...loc,...v};try{localStorage.setItem('elev8mi-location',JSON.stringify(loc))}catch(_){};window.dispatchEvent(new CustomEvent('elev8mi:location',{detail:loc}));updateEarth();}};
function updateEarth(){const e=document.querySelector('.earth-location');if(!e)return;const text=`VIEW FROM · ${loc.label||`${loc.lat.toFixed(2)}, ${loc.lon.toFixed(2)}`}`;const label=`Sky view from ${loc.label}. Change location`;if(e.textContent!==text)e.textContent=text;if(e.getAttribute('aria-label')!==label)e.setAttribute('aria-label',label);}
const dlg=document.createElement('dialog');dlg.id='locationDialog';dlg.innerHTML='<button id="locationClose" type="button" aria-label="Close">×</button><h2>Your view of the sky</h2><p>The stars can rotate for your longitude. Use your device location, or enter latitude and longitude.</p><div class="location-actions"><button id="useLocation" type="button">Use my location</button><div class="location-coords"><input id="locLat" inputmode="decimal" aria-label="Latitude" placeholder="Latitude"><input id="locLon" inputmode="decimal" aria-label="Longitude" placeholder="Longitude"></div><input id="locLabel" aria-label="Location name" placeholder="Location name (optional)"><button id="setLocation" type="button">Set view</button><button id="resetLocation" type="button">Use New York City</button></div><p id="locationStatus" class="location-status" role="status"></p>';document.body.append(dlg);
function openLoc(){dlg.querySelector('#locLat').value=loc.lat;dlg.querySelector('#locLon').value=loc.lon;dlg.querySelector('#locLabel').value=loc.label;dlg.showModal?.();}document.addEventListener('click',e=>{if(e.target.closest?.('.earth-location')){e.preventDefault();openLoc();}});dlg.querySelector('#locationClose').onclick=()=>dlg.close();dlg.querySelector('#resetLocation').onclick=()=>{window.Elev8Location.set(DEFAULT);dlg.close()};dlg.querySelector('#setLocation').onclick=()=>{const lat=+dlg.querySelector('#locLat').value,lon=+dlg.querySelector('#locLon').value,label=dlg.querySelector('#locLabel').value.trim();if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180){dlg.querySelector('#locationStatus').textContent='Enter a valid latitude and longitude.';return}window.Elev8Location.set({lat,lon,label:label||`${lat.toFixed(2)}°, ${lon.toFixed(2)}°`});dlg.close()};dlg.querySelector('#useLocation').onclick=()=>{const status=dlg.querySelector('#locationStatus');if(!navigator.geolocation){status.textContent='Location sharing is unavailable in this browser.';return}status.textContent='Requesting your location…';navigator.geolocation.getCurrentPosition(p=>{const lat=p.coords.latitude,lon=p.coords.longitude;window.Elev8Location.set({lat,lon,label:'My location'});status.textContent='Location updated.';setTimeout(()=>dlg.close(),350)},()=>status.textContent='Location permission was not granted.',{enableHighAccuracy:false,timeout:9000,maximumAge:600000})};
const earthWatch=new MutationObserver(updateEarth);earthWatch.observe(document.getElementById('solarBodies')||document.body,{childList:true,subtree:true});updateEarth();
// True local sidereal rotation from longitude; zeroed against NYC so v35's framing is preserved there.
function gmst(d){const jd=d.getTime()/86400000+2440587.5,x=jd-2451545,T=x/36525;return ((280.46061837+360.98564736629*x+.000387933*T*T-T*T*T/38710000)%360+360)%360}function skyRotation(){if(!window.Elev8Sky)return;const now=new Date(),base=(gmst(now)+DEFAULT.lon+360)%360,here=(gmst(now)+loc.lon+360)%360;window.Elev8Sky.rotation=(here-base)*Math.PI/180}setInterval(skyRotation,1000);window.addEventListener('elev8mi:location',skyRotation);skyRotation();
})();
